export const PRESENTATION_DEFAULT_THEME = {
  id: "default",
  fonts: {
    heading: "Georgia",
    body: "Arial",
  },
  colors: {
    background: "F7F3EC",
    text: "1F2320",
    muted: "6F6258",
    border: "D8CABB",
    surface: "EFE8DD",
    card: "FFFDF8",
    accent: "8F3D2E",
    accentSoft: "E8D8C8",
    chart: ["8F3D2E", "6F6258", "B57A4A", "47543F", "C5A572", "7C4A3A"],
  },
  typography: {
    title: 30,
    subtitle: 18,
    body: 13,
    bullets: 14,
    cardTitle: 17,
    cardBody: 14.5,
    table: 8,
    chart: 9,
    placeholder: 11,
  },
  spacing: {
    cardGap: 0.12,
    cardPadding: 0.12,
    cardTitleGap: 0.08,
    bulletGap: 0.12,
    bulletMarkerWidth: 0.06,
    bulletMarkerHeight: 0.18,
    bulletTextGap: 0.16,
    titleAccentGap: 0.08,
    titleAccentHeight: 0.035,
    titleAccentWidth: 1.2,
    tableCellMargin: 3,
    textMargin: 4,
  },
} as const;

export type PresentationTheme = typeof PRESENTATION_DEFAULT_THEME;
