export const PRESENTATION_DEFAULT_THEME = {
  id: "default",
  fonts: {
    heading: "Georgia",
    body: "Arial",
  },
  colors: {
    background: "F7F3EC",
    text: "243D4C",
    muted: "425969",
    border: "E7DECF",
    surface: "EFE9DE",
    card: "EFE8DA",
    accent: "0F4F73",
    accentSoft: "DCD4C6",
    chart: ["0F4F73", "42708A", "86A6B6", "B57A4A", "6F8068", "D3B278"],
  },
  typography: {
    title: 32,
    subtitle: 18,
    body: 13,
    bullets: 15,
    cardTitle: 17,
    cardBody: 14.5,
    metric: 42,
    table: 8,
    chart: 9,
    placeholder: 11,
  },
  spacing: {
    cardGap: 0.18,
    cardPadding: 0.22,
    cardTitleGap: 0.12,
    cardIconSize: 0.48,
    cardIconGap: 0.22,
    bulletGap: 0.3,
    bulletMarkerWidth: 0.42,
    bulletMarkerHeight: 0.32,
    bulletTextGap: 0.18,
    titleAccentGap: 0.08,
    titleAccentHeight: 0.028,
    titleAccentWidth: 1.2,
    tableCellMargin: 3,
    textMargin: 4,
  },
} as const;

export type PresentationTheme = typeof PRESENTATION_DEFAULT_THEME;
